### ISSUE TITLE
Request of  your train code model.

### ISSUE THREAD

**Issue by ss0415** [sniklaus/pytorch-sepconv#18] opened 2018-07-17 11:53 UTC
I'm intersted in your work,but there is no how to train the model.If you can offer it,I'll very thank you.

**Comment by meipuru344** [comment] 2019-02-04 05:44
https://github.com/meipuru344/sepconv
I wrote train code.
You can check it out :)

**Comment by l2009312042** [comment] 2019-04-24 12:59
@meipuru344  follow your work ,i fix some bug and   write the train code  to train pic 
https://github.com/l2009312042/sepconv

**Comment by sniklaus** [comment] 2020-01-24 19:03
Thank you for being interested in our work! I am closing this since it is a duplicate of #3 and since there are a few forks, like the one from @meipuru344, who show how to do training with adaptive separable convolutions. This may also be a worthwhile read: https://arxiv.org/abs/1809.07759

**Closed as completed by sniklaus** 2020-01-24 19:03 UTC
